# Generated by Django 6.1.1 on 2026-10-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turf', '0002_alter_turf_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_endtime', models.TimeField(editable=False, null=True)),
                ('duration', models.DurationField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf')),
            ],
        ),
    ]
