
# api call for admin registration
###
POST http://127.0.0.1:8000/turf/admin-register/
Content-Type: application/json

{
    "username":"adminuser",
    "email":"adminuser@gmail.com",
    "password":"admin123"
}

# api call for listing turf details
###
GET http://127.0.0.1:8000/turf/
Accept: application/json
Authorization: Basic adminuser:admin123

# api call for creating turf details
###
POST  http://127.0.0.1:8000/turf/
Content-Type: application/json
Authorization: Basic adminuser:admin123

{
    "name":"game on",
    "location":"palakkad",
    "phone":"147258369",
    "fee":1000
}

# api call for listing one turf details
###
GET http://127.0.0.1:8000/turf/1/
Accept: application/json
Authorization: Basic adminuser:admin123

# api call for updating turf details
###
POST  http://127.0.0.1:8000/turf/3/
Content-Type: application/json
Authorization: Basic adminuser:admin123

{
    "name":"rosario",
    "location":"malappuram",
    "phone":"147258369",
    "fee":1000
}

# api call for deleting one turf details
###
DELETE  http://127.0.0.1:8000/turf/4/
Accept: application/json
Authorization: Basic adminuser:admin123

# ==========Booking================

# api call for listing booking details
###
GET http://127.0.0.1:8000/bookings/
Accept: application/json

# api call for creating booking details
###
POST http://127.0.0.1:8000/bookings/
Content-Type: application/json

{
    "team_name":"inter milan",
    "phone":123456789,
    "turf":1,
    "booking_date":"2026-10-2",
    "booking_time":"8:00:00",
    "duration":"1:00:00"
}

# api call for listing one booking details
###
GET http://127.0.0.1:8000/bookings/1/
Accept: application/json

# api call for updating booking details
###
POST http://127.0.0.1:8000/bookings/1/
Content-Type: application/json

{
    "team_name": "fc barselona",
    "phone": "598746123",
    "turf": 1,
    "booking_date": "2026-10-05",
    "booking_time": "11:00:00",
    "duration": "01:00:00"
}

# api call for deleting one booking details
###
DELETE http://127.0.0.1:8000/bookings/4/
Accept: application/json


############ slot_v2 ########
# api call for user authentictaion
###
POST http://127.0.0.1:8000/v2/booking/signup/
Content-Type: application/json

{
    "username":"django",
    "email":"django@gmail.com",
    "password":"django123"
}

# api call for listing booking details
###
GET http://127.0.0.1:8000/v2/booking/slotv2/
Accept: application/json

# api call for creating booking details
###
POST http://127.0.0.1:8000/v2/booking/slotv2/
Content-Type: application/json

{
    "team_name":"barca",
    "phone":123456789,
    "turf":1,
    "booking_date":"2026-10-06",
    "booking_time":"11:00:00",
    "duration":"1:00:00"
}