# Generated by Django 6.1.1 on 2026-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
