# Generated by Django 6.1.1 on 2026-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.DurationField(),
        ),
    ]
