# Generated by Django 6.1.1 on 2026-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_alter_booking_booking_time_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
    ]
